SET NAMES utf8;

DROP DATABASE IF EXISTS momohr;

CREATE DATABASE IF NOT EXISTS momohr CHARSET=utf8;

USE momohr;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
    uname VARCHAR(50) NOT NULL,
    upwd VARCHAR(50) NOT NULL
);

INSERT INTO users VALUES(1, 'zdsherlock', '12345678');